version: "3"

services:    
    server-api:
        build: 
            context: src/server/
        ports:
            - "8000:80"
        restart: always
    client_react-web:
        build: 
            context: src/client/
        ports:
            - "8001:3000"
        restart: always
    host:
        build: 
            context: src/nginx/
        ports:
            - "3000:80"
        restart: always
        depends_on: 
            - client_react-web
            - server-api
